services:
  reservations-service:
    container_name: reservations-service
    build:
      context: .
      dockerfile: ./apps/reservations-service/Dockerfile
      target: development
    command: pnpm run start:dev reservations-service
    env_file:
      - ./apps/reservations-service/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth-service
    env_file:
      - ./apps/auth/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
